{% set name = "elemental-core" %}
{% set version = "0.2.0dev0" %}
{% set md5 = "aff4e61712757b65e670e382a28dd433" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  skip: True  # [py<3]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - elemental_core

about:
  home: https://github.com/artPlusPlus/elemental-core
  summary: 'Functionality shared across Elemental CMS.'
  license: MPL 2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - artPlusPlus
